### PR TITLE
Update to v1.8.1

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
@jjhelmus could you please take a look at this? Similar commit is in conda-forge: https://github.com/conda-forge/sphinx-feedstock/commit/3698ae414ddbc28e0ec2b9caf7993f692aeee50c#diff-e178b687b10a71a3348107ae3154e44c

**Comment by 183amir** [comment]
ping @tiagofrepereira2012

**Comment by tiagofrepereira2012** [comment]
Thanks @183amir

**Comment by jjhelmus** [comment]
I've rebased this feedstock against `conda-forge` and picked up the 1.8.1 release.  Packages are available in `defaults`

**Pull request closed without merging**
